export type CiudadMexico = {
  nombre: string;
  municipios?: string[];
};

export type EstadoMexico = {
  nombre: string;
  ciudades: CiudadMexico[];
};

export const estadosMexico: EstadoMexico[] = [
  {
    nombre: "Aguascalientes",
    ciudades: [
      { nombre: "Aguascalientes", municipios: ["Aguascalientes"] },
      { nombre: "Jesús María", municipios: ["Jesús María"] },
      { nombre: "Calvillo", municipios: ["Calvillo"] },
      { nombre: "Rincón de Romos", municipios: ["Rincón de Romos"] },
      { nombre: "Pabellón de Arteaga", municipios: ["Pabellón de Arteaga"] },
      { nombre: "San Francisco de los Romo", municipios: ["San Francisco de los Romo"] },
      { nombre: "Asientos", municipios: ["Asientos"] },
      { nombre: "Tepezalá", municipios: ["Tepezalá"] },
      { nombre: "San José de Gracia", municipios: ["San José de Gracia"] },
      { nombre: "El Llano", municipios: ["El Llano"] },
    ],
  },
  {
    nombre: "Baja California",
    ciudades: [
      { nombre: "Mexicali", municipios: ["Mexicali", "San Felipe"] },
      { nombre: "Tijuana", municipios: ["Tijuana"] },
      { nombre: "Ensenada", municipios: ["Ensenada", "San Quintín"] },
      { nombre: "Tecate", municipios: ["Tecate"] },
      { nombre: "Playas de Rosarito", municipios: ["Playas de Rosarito"] },
    ],
  },
  {
    nombre: "Baja California Sur",
    ciudades: [
      { nombre: "La Paz", municipios: ["La Paz"] },
      { nombre: "Cabo San Lucas", municipios: ["Los Cabos"] },
      { nombre: "San José del Cabo", municipios: ["Los Cabos"] },
      { nombre: "Ciudad Constitución", municipios: ["Comondú"] },
      { nombre: "Loreto", municipios: ["Loreto"] },
      { nombre: "Santa Rosalía", municipios: ["Mulegé"] },
    ],
  },
  {
    nombre: "Campeche",
    ciudades: [
      { nombre: "San Francisco de Campeche", municipios: ["Campeche"] },
      { nombre: "Ciudad del Carmen", municipios: ["Carmen"] },
      { nombre: "Champotón", municipios: ["Champotón"] },
      { nombre: "Escárcega", municipios: ["Escárcega"] },
      { nombre: "Calkiní", municipios: ["Calkiní"] },
      { nombre: "Hopelchén", municipios: ["Hopelchén"] },
      { nombre: "Hecelchakán", municipios: ["Hecelchakán"] },
      { nombre: "Palizada", municipios: ["Palizada"] },
    ],
  },
  {
    nombre: "Chiapas",
    ciudades: [
      { nombre: "Tuxtla Gutiérrez", municipios: ["Tuxtla Gutiérrez"] },
      { nombre: "San Cristóbal de las Casas", municipios: ["San Cristóbal de las Casas"] },
      { nombre: "Tapachula", municipios: ["Tapachula"] },
      { nombre: "Comitán de Domínguez", municipios: ["Comitán de Domínguez"] },
      { nombre: "Palenque", municipios: ["Palenque"] },
      { nombre: "Ocosingo", municipios: ["Ocosingo"] },
      { nombre: "Villaflores", municipios: ["Villaflores"] },
      { nombre: "Tonalá", municipios: ["Tonalá"] },
      { nombre: "Chiapa de Corzo", municipios: ["Chiapa de Corzo"] },
      { nombre: "Cintalapa", municipios: ["Cintalapa"] },
      { nombre: "Pichucalco", municipios: ["Pichucalco"] },
      { nombre: "Arriaga", municipios: ["Arriaga"] },
    ],
  },
  {
    nombre: "Chihuahua",
    ciudades: [
      { nombre: "Chihuahua", municipios: ["Chihuahua"] },
      { nombre: "Ciudad Juárez", municipios: ["Juárez"] },
      { nombre: "Cuauhtémoc", municipios: ["Cuauhtémoc"] },
      { nombre: "Delicias", municipios: ["Delicias"] },
      { nombre: "Hidalgo del Parral", municipios: ["Hidalgo del Parral"] },
      { nombre: "Nuevo Casas Grandes", municipios: ["Nuevo Casas Grandes"] },
      { nombre: "Camargo", municipios: ["Camargo"] },
      { nombre: "Jiménez", municipios: ["Jiménez"] },
      { nombre: "Ojinaga", municipios: ["Ojinaga"] },
      { nombre: "Meoqui", municipios: ["Meoqui"] },
    ],
  },
  {
    nombre: "Ciudad de México",
    ciudades: [
      { nombre: "Álvaro Obregón", municipios: ["Álvaro Obregón"] },
      { nombre: "Azcapotzalco", municipios: ["Azcapotzalco"] },
      { nombre: "Benito Juárez", municipios: ["Benito Juárez"] },
      { nombre: "Coyoacán", municipios: ["Coyoacán"] },
      { nombre: "Cuajimalpa de Morelos", municipios: ["Cuajimalpa de Morelos"] },
      { nombre: "Cuauhtémoc", municipios: ["Cuauhtémoc"] },
      { nombre: "Gustavo A. Madero", municipios: ["Gustavo A. Madero"] },
      { nombre: "Iztacalco", municipios: ["Iztacalco"] },
      { nombre: "Iztapalapa", municipios: ["Iztapalapa"] },
      { nombre: "La Magdalena Contreras", municipios: ["La Magdalena Contreras"] },
      { nombre: "Miguel Hidalgo", municipios: ["Miguel Hidalgo"] },
      { nombre: "Milpa Alta", municipios: ["Milpa Alta"] },
      { nombre: "Tláhuac", municipios: ["Tláhuac"] },
      { nombre: "Tlalpan", municipios: ["Tlalpan"] },
      { nombre: "Venustiano Carranza", municipios: ["Venustiano Carranza"] },
      { nombre: "Xochimilco", municipios: ["Xochimilco"] },
    ],
  },
  {
    nombre: "Coahuila",
    ciudades: [
      { nombre: "Saltillo", municipios: ["Saltillo"] },
      { nombre: "Torreón", municipios: ["Torreón"] },
      { nombre: "Monclova", municipios: ["Monclova"] },
      { nombre: "Piedras Negras", municipios: ["Piedras Negras"] },
      { nombre: "Ciudad Acuña", municipios: ["Acuña"] },
      { nombre: "Ramos Arizpe", municipios: ["Ramos Arizpe"] },
      { nombre: "San Pedro", municipios: ["San Pedro"] },
      { nombre: "Frontera", municipios: ["Frontera"] },
      { nombre: "Sabinas", municipios: ["Sabinas"] },
      { nombre: "Múzquiz", municipios: ["Múzquiz"] },
    ],
  },
  {
    nombre: "Colima",
    ciudades: [
      { nombre: "Colima", municipios: ["Colima"] },
      { nombre: "Manzanillo", municipios: ["Manzanillo"] },
      { nombre: "Villa de Álvarez", municipios: ["Villa de Álvarez"] },
      { nombre: "Tecomán", municipios: ["Tecomán"] },
      { nombre: "Armería", municipios: ["Armería"] },
      { nombre: "Comala", municipios: ["Comala"] },
      { nombre: "Cuauhtémoc", municipios: ["Cuauhtémoc"] },
    ],
  },
  {
    nombre: "Durango",
    ciudades: [
      { nombre: "Victoria de Durango", municipios: ["Durango"] },
      { nombre: "Gómez Palacio", municipios: ["Gómez Palacio"] },
      { nombre: "Lerdo", municipios: ["Lerdo"] },
      { nombre: "Santiago Papasquiaro", municipios: ["Santiago Papasquiaro"] },
      { nombre: "El Salto", municipios: ["Pueblo Nuevo"] },
      { nombre: "Canatlán", municipios: ["Canatlán"] },
      { nombre: "Nombre de Dios", municipios: ["Nombre de Dios"] },
      { nombre: "Guadalupe Victoria", municipios: ["Guadalupe Victoria"] },
    ],
  },
  {
    nombre: "Estado de México",
    ciudades: [
      { nombre: "Toluca", municipios: ["Toluca"] },
      { nombre: "Ecatepec de Morelos", municipios: ["Ecatepec de Morelos"] },
      { nombre: "Naucalpan de Juárez", municipios: ["Naucalpan de Juárez"] },
      { nombre: "Nezahualcóyotl", municipios: ["Nezahualcóyotl"] },
      { nombre: "Metepec", municipios: ["Metepec"] },
      { nombre: "Tlalnepantla de Baz", municipios: ["Tlalnepantla de Baz"] },
      { nombre: "Cuautitlán Izcalli", municipios: ["Cuautitlán Izcalli"] },
      { nombre: "Texcoco", municipios: ["Texcoco"] },
      { nombre: "Chimalhuacán", municipios: ["Chimalhuacán"] },
      { nombre: "Atizapán de Zaragoza", municipios: ["Atizapán de Zaragoza"] },
      { nombre: "Ixtapaluca", municipios: ["Ixtapaluca"] },
      { nombre: "Valle de Bravo", municipios: ["Valle de Bravo"] },
      { nombre: "Zinacantepec", municipios: ["Zinacantepec"] },
    ],
  },
  {
    nombre: "Guanajuato",
    ciudades: [
      { nombre: "Guanajuato", municipios: ["Guanajuato"] },
      { nombre: "León", municipios: ["León"] },
      { nombre: "Irapuato", municipios: ["Irapuato"] },
      { nombre: "Celaya", municipios: ["Celaya"] },
      { nombre: "Salamanca", municipios: ["Salamanca"] },
      { nombre: "San Miguel de Allende", municipios: ["San Miguel de Allende"] },
      { nombre: "Dolores Hidalgo", municipios: ["Dolores Hidalgo Cuna de la Independencia Nacional"] },
      { nombre: "Silao", municipios: ["Silao de la Victoria"] },
      { nombre: "San Francisco del Rincón", municipios: ["San Francisco del Rincón"] },
      { nombre: "Pénjamo", municipios: ["Pénjamo"] },
    ],
  },
  {
    nombre: "Guerrero",
    ciudades: [
      { nombre: "Chilpancingo de los Bravo", municipios: ["Chilpancingo de los Bravo"] },
      { nombre: "Acapulco", municipios: ["Acapulco de Juárez"] },
      { nombre: "Iguala", municipios: ["Iguala de la Independencia"] },
      { nombre: "Taxco", municipios: ["Taxco de Alarcón"] },
      { nombre: "Zihuatanejo", municipios: ["Zihuatanejo de Azueta"] },
      { nombre: "Ciudad Altamirano", municipios: ["Pungarabato"] },
      { nombre: "Petatlán", municipios: ["Petatlán"] },
      { nombre: "Atoyac de Álvarez", municipios: ["Atoyac de Álvarez"] },
      { nombre: "Tlapa de Comonfort", municipios: ["Tlapa de Comonfort"] },
    ],
  },
  {
    nombre: "Hidalgo",
    ciudades: [
      { nombre: "Pachuca de Soto", municipios: ["Pachuca de Soto"] },
      { nombre: "Tulancingo de Bravo", municipios: ["Tulancingo de Bravo"] },
      { nombre: "Tula de Allende", municipios: ["Tula de Allende"] },
      { nombre: "Actopan", municipios: ["Actopan"] },
      { nombre: "Ixmiquilpan", municipios: ["Ixmiquilpan"] },
      { nombre: "Huejutla de Reyes", municipios: ["Huejutla de Reyes"] },
      { nombre: "Mineral de la Reforma", municipios: ["Mineral de la Reforma"] },
      { nombre: "Tizayuca", municipios: ["Tizayuca"] },
      { nombre: "Tepeji del Río", municipios: ["Tepeji del Río de Ocampo"] },
      { nombre: "Zimapán", municipios: ["Zimapán"] },
      { nombre: "Apan", municipios: ["Apan"] },
      { nombre: "Huichapan", municipios: ["Huichapan"] },
    ],
  },
  {
    nombre: "Jalisco",
    ciudades: [
      { nombre: "Guadalajara", municipios: ["Guadalajara"] },
      { nombre: "Zapopan", municipios: ["Zapopan"] },
      { nombre: "San Pedro Tlaquepaque", municipios: ["San Pedro Tlaquepaque"] },
      { nombre: "Tonalá", municipios: ["Tonalá"] },
      { nombre: "Puerto Vallarta", municipios: ["Puerto Vallarta"] },
      { nombre: "Lagos de Moreno", municipios: ["Lagos de Moreno"] },
      { nombre: "Tepatitlán de Morelos", municipios: ["Tepatitlán de Morelos"] },
      { nombre: "Colotlán", municipios: ["Colotlán"] },
      { nombre: "Ciudad Guzmán", municipios: ["Zapotlán el Grande"] },
      { nombre: "Ocotlán", municipios: ["Ocotlán"] },
      { nombre: "Autlán de Navarro", municipios: ["Autlán de Navarro"] },
      { nombre: "Tequila", municipios: ["Tequila"] },
      { nombre: "Arandas", municipios: ["Arandas"] },
      { nombre: "Ameca", municipios: ["Ameca"] },
      { nombre: "La Barca", municipios: ["La Barca"] },
      { nombre: "Chapala", municipios: ["Chapala"] },
      { nombre: "Cihuatlán", municipios: ["Cihuatlán"] },
    ],
  },
  {
    nombre: "Michoacán",
    ciudades: [
      { nombre: "Morelia", municipios: ["Morelia"] },
      { nombre: "Uruapan", municipios: ["Uruapan"] },
      { nombre: "Zamora", municipios: ["Zamora"] },
      { nombre: "Lázaro Cárdenas", municipios: ["Lázaro Cárdenas"] },
      { nombre: "Pátzcuaro", municipios: ["Pátzcuaro"] },
      { nombre: "Apatzingán", municipios: ["Apatzingán"] },
      { nombre: "Zitácuaro", municipios: ["Zitácuaro"] },
      { nombre: "La Piedad", municipios: ["La Piedad"] },
      { nombre: "Sahuayo", municipios: ["Sahuayo"] },
      { nombre: "Puruándiro", municipios: ["Puruándiro"] },
      { nombre: "Tacámbaro", municipios: ["Tacámbaro"] },
    ],
  },
  {
    nombre: "Morelos",
    ciudades: [
      { nombre: "Cuernavaca", municipios: ["Cuernavaca"] },
      { nombre: "Jiutepec", municipios: ["Jiutepec"] },
      { nombre: "Cuautla", municipios: ["Cuautla"] },
      { nombre: "Temixco", municipios: ["Temixco"] },
      { nombre: "Yautepec", municipios: ["Yautepec"] },
      { nombre: "Tepoztlán", municipios: ["Tepoztlán"] },
      { nombre: "Jojutla", municipios: ["Jojutla"] },
      { nombre: "Xochitepec", municipios: ["Xochitepec"] },
      { nombre: "Emiliano Zapata", municipios: ["Emiliano Zapata"] },
    ],
  },
  {
    nombre: "Nayarit",
    ciudades: [
      { nombre: "Tepic", municipios: ["Tepic"] },
      { nombre: "Bahía de Banderas", municipios: ["Bahía de Banderas"] },
      { nombre: "Santiago Ixcuintla", municipios: ["Santiago Ixcuintla"] },
      { nombre: "Compostela", municipios: ["Compostela"] },
      { nombre: "Acaponeta", municipios: ["Acaponeta"] },
      { nombre: "Ixtlán del Río", municipios: ["Ixtlán del Río"] },
      { nombre: "San Blas", municipios: ["San Blas"] },
    ],
  },
  {
    nombre: "Nuevo León",
    ciudades: [
      { nombre: "Monterrey", municipios: ["Monterrey"] },
      { nombre: "San Pedro Garza García", municipios: ["San Pedro Garza García"] },
      { nombre: "Guadalupe", municipios: ["Guadalupe"] },
      { nombre: "San Nicolás de los Garza", municipios: ["San Nicolás de los Garza"] },
      { nombre: "Apodaca", municipios: ["Apodaca"] },
      { nombre: "General Escobedo", municipios: ["General Escobedo"] },
      { nombre: "Santa Catarina", municipios: ["Santa Catarina"] },
      { nombre: "Juárez", municipios: ["Juárez"] },
      { nombre: "García", municipios: ["García"] },
      { nombre: "Cadereyta Jiménez", municipios: ["Cadereyta Jiménez"] },
      { nombre: "Linares", municipios: ["Linares"] },
      { nombre: "Montemorelos", municipios: ["Montemorelos"] },
    ],
  },
  {
    nombre: "Oaxaca",
    ciudades: [
      { nombre: "Oaxaca de Juárez", municipios: ["Oaxaca de Juárez"] },
      { nombre: "Salina Cruz", municipios: ["Salina Cruz"] },
      { nombre: "Juchitán de Zaragoza", municipios: ["Heroica Ciudad de Juchitán de Zaragoza"] },
      { nombre: "San Juan Bautista Tuxtepec", municipios: ["San Juan Bautista Tuxtepec"] },
      { nombre: "Huajuapan de León", municipios: ["Heroica Ciudad de Huajuapan de León"] },
      { nombre: "Puerto Escondido", municipios: ["San Pedro Mixtepec"] },
      { nombre: "Santa María Huatulco", municipios: ["Santa María Huatulco"] },
      { nombre: "Miahuatlán de Porfirio Díaz", municipios: ["Miahuatlán de Porfirio Díaz"] },
      { nombre: "Tlaxiaco", municipios: ["Heroica Ciudad de Tlaxiaco"] },
      { nombre: "Tehuantepec", municipios: ["Santo Domingo Tehuantepec"] },
      { nombre: "Putla Villa de Guerrero", municipios: ["Putla Villa de Guerrero"] },
    ],
  },
  {
    nombre: "Puebla",
    ciudades: [
      { nombre: "Puebla", municipios: ["Puebla"] },
      { nombre: "Tehuacán", municipios: ["Tehuacán"] },
      { nombre: "San Martín Texmelucan", municipios: ["San Martín Texmelucan"] },
      { nombre: "Atlixco", municipios: ["Atlixco"] },
      { nombre: "San Pedro Cholula", municipios: ["San Pedro Cholula"] },
      { nombre: "Teziutlán", municipios: ["Teziutlán"] },
      { nombre: "Huauchinango", municipios: ["Huauchinango"] },
      { nombre: "Izúcar de Matamoros", municipios: ["Izúcar de Matamoros"] },
      { nombre: "Cholula de Rivadavia", municipios: ["San Pedro Cholula"] },
      { nombre: "Xicotepec", municipios: ["Xicotepec"] },
      { nombre: "Zacatlán", municipios: ["Zacatlán"] },
      { nombre: "Amozoc", municipios: ["Amozoc"] },
    ],
  },
  {
    nombre: "Querétaro",
    ciudades: [
      { nombre: "Santiago de Querétaro", municipios: ["Querétaro"] },
      { nombre: "San Juan del Río", municipios: ["San Juan del Río"] },
      { nombre: "El Marqués", municipios: ["El Marqués"] },
      { nombre: "Corregidora", municipios: ["Corregidora"] },
      { nombre: "Cadereyta de Montes", municipios: ["Cadereyta de Montes"] },
      { nombre: "Tequisquiapan", municipios: ["Tequisquiapan"] },
      { nombre: "San Joaquín", municipios: ["San Joaquín"] },
      { nombre: "Jalpan de Serra", municipios: ["Jalpan de Serra"] },
    ],
  },
  {
    nombre: "Quintana Roo",
    ciudades: [
      { nombre: "Chetumal", municipios: ["Othón P. Blanco"] },
      { nombre: "Cancún", municipios: ["Benito Juárez"] },
      { nombre: "Playa del Carmen", municipios: ["Solidaridad"] },
      { nombre: "Tulum", municipios: ["Tulum"] },
      { nombre: "Cozumel", municipios: ["Cozumel"] },
      { nombre: "Isla Mujeres", municipios: ["Isla Mujeres"] },
      { nombre: "Felipe Carrillo Puerto", municipios: ["Felipe Carrillo Puerto"] },
      { nombre: "Bacalar", municipios: ["Bacalar"] },
      { nombre: "Puerto Morelos", municipios: ["Puerto Morelos"] },
    ],
  },
  {
    nombre: "San Luis Potosí",
    ciudades: [
      { nombre: "San Luis Potosí", municipios: ["San Luis Potosí"] },
      { nombre: "Soledad de Graciano Sánchez", municipios: ["Soledad de Graciano Sánchez"] },
      { nombre: "Ciudad Valles", municipios: ["Ciudad Valles"] },
      { nombre: "Matehuala", municipios: ["Matehuala"] },
      { nombre: "Rioverde", municipios: ["Rioverde"] },
      { nombre: "Tamazunchale", municipios: ["Tamazunchale"] },
      { nombre: "Ciudad Fernández", municipios: ["Ciudad Fernández"] },
      { nombre: "Ébano", municipios: ["Ébano"] },
    ],
  },
  {
    nombre: "Sinaloa",
    ciudades: [
      { nombre: "Culiacán", municipios: ["Culiacán"] },
      { nombre: "Mazatlán", municipios: ["Mazatlán"] },
      { nombre: "Los Mochis", municipios: ["Ahome"] },
      { nombre: "Guasave", municipios: ["Guasave"] },
      { nombre: "Navolato", municipios: ["Navolato"] },
      { nombre: "El Fuerte", municipios: ["El Fuerte"] },
      { nombre: "Guamúchil", municipios: ["Salvador Alvarado"] },
      { nombre: "Escuinapa", municipios: ["Escuinapa"] },
      { nombre: "Rosario", municipios: ["Rosario"] },
    ],
  },
  {
    nombre: "Sonora",
    ciudades: [
      { nombre: "Hermosillo", municipios: ["Hermosillo"] },
      { nombre: "Ciudad Obregón", municipios: ["Cajeme"] },
      { nombre: "Nogales", municipios: ["Nogales"] },
      { nombre: "San Luis Río Colorado", municipios: ["San Luis Río Colorado"] },
      { nombre: "Navojoa", municipios: ["Navojoa"] },
      { nombre: "Guaymas", municipios: ["Guaymas"] },
      { nombre: "Puerto Peñasco", municipios: ["Puerto Peñasco"] },
      { nombre: "Agua Prieta", municipios: ["Agua Prieta"] },
      { nombre: "Caborca", municipios: ["Caborca"] },
      { nombre: "Cananea", municipios: ["Cananea"] },
    ],
  },
  {
    nombre: "Tabasco",
    ciudades: [
      { nombre: "Villahermosa", municipios: ["Centro"] },
      { nombre: "Cárdenas", municipios: ["Cárdenas"] },
      { nombre: "Comalcalco", municipios: ["Comalcalco"] },
      { nombre: "Paraíso", municipios: ["Paraíso"] },
      { nombre: "Macuspana", municipios: ["Macuspana"] },
      { nombre: "Tenosique", municipios: ["Tenosique"] },
      { nombre: "Huimanguillo", municipios: ["Huimanguillo"] },
      { nombre: "Nacajuca", municipios: ["Nacajuca"] },
    ],
  },
  {
    nombre: "Tamaulipas",
    ciudades: [
      { nombre: "Ciudad Victoria", municipios: ["Victoria"] },
      { nombre: "Tampico", municipios: ["Tampico"] },
      { nombre: "Reynosa", municipios: ["Reynosa"] },
      { nombre: "Matamoros", municipios: ["Matamoros"] },
      { nombre: "Nuevo Laredo", municipios: ["Nuevo Laredo"] },
      { nombre: "Ciudad Madero", municipios: ["Ciudad Madero"] },
      { nombre: "Altamira", municipios: ["Altamira"] },
      { nombre: "El Mante", municipios: ["El Mante"] },
      { nombre: "Río Bravo", municipios: ["Río Bravo"] },
      { nombre: "San Fernando", municipios: ["San Fernando"] },
    ],
  },
  {
    nombre: "Tlaxcala",
    ciudades: [
      { nombre: "Tlaxcala de Xicohténcatl", municipios: ["Tlaxcala"] },
      { nombre: "Apizaco", municipios: ["Apizaco"] },
      { nombre: "Huamantla", municipios: ["Huamantla"] },
      { nombre: "Chiautempan", municipios: ["Chiautempan"] },
      { nombre: "Calpulalpan", municipios: ["Calpulalpan"] },
      { nombre: "Zacatelco", municipios: ["Zacatelco"] },
      { nombre: "Tlaxco", municipios: ["Tlaxco"] },
    ],
  },
  {
    nombre: "Veracruz",
    ciudades: [
      { nombre: "Xalapa", municipios: ["Xalapa"] },
      { nombre: "Veracruz", municipios: ["Veracruz"] },
      { nombre: "Coatzacoalcos", municipios: ["Coatzacoalcos"] },
      { nombre: "Córdoba", municipios: ["Córdoba"] },
      { nombre: "Orizaba", municipios: ["Orizaba"] },
      { nombre: "Poza Rica", municipios: ["Poza Rica de Hidalgo"] },
      { nombre: "Boca del Río", municipios: ["Boca del Río"] },
      { nombre: "Tuxpan", municipios: ["Tuxpan"] },
      { nombre: "Minatitlán", municipios: ["Minatitlán"] },
      { nombre: "Papantla", municipios: ["Papantla"] },
      { nombre: "Martínez de la Torre", municipios: ["Martínez de la Torre"] },
      { nombre: "San Andrés Tuxtla", municipios: ["San Andrés Tuxtla"] },
    ],
  },
  {
    nombre: "Yucatán",
    ciudades: [
      { nombre: "Mérida", municipios: ["Mérida"] },
      { nombre: "Valladolid", municipios: ["Valladolid"] },
      { nombre: "Progreso", municipios: ["Progreso"] },
      { nombre: "Tizimín", municipios: ["Tizimín"] },
      { nombre: "Motul", municipios: ["Motul"] },
      { nombre: "Umán", municipios: ["Umán"] },
      { nombre: "Kanasín", municipios: ["Kanasín"] },
      { nombre: "Tekax", municipios: ["Tekax"] },
      { nombre: "Izamal", municipios: ["Izamal"] },
      { nombre: "Ticul", municipios: ["Ticul"] },
    ],
  },
  {
    nombre: "Zacatecas",
    ciudades: [
      { nombre: "Zacatecas", municipios: ["Zacatecas"] },
      { nombre: "Guadalupe", municipios: ["Guadalupe"] },
      { nombre: "Fresnillo", municipios: ["Fresnillo"] },
      { nombre: "Jerez de García Salinas", municipios: ["Jerez"] },
      { nombre: "Río Grande", municipios: ["Río Grande"] },
      { nombre: "Sombrerete", municipios: ["Sombrerete"] },
      { nombre: "Calera de Víctor Rosales", municipios: ["Calera"] },
      { nombre: "Loreto", municipios: ["Loreto"] },
      { nombre: "Ojocaliente", municipios: ["Ojocaliente"] },
      { nombre: "Pinos", municipios: ["Pinos"] },
    ],
  },
];

export const nombresEstadosMexico = estadosMexico.map(
  (estado) => estado.nombre,
);

export function obtenerCiudadesPorEstado(
  nombreEstado: string,
): CiudadMexico[] {
  return (
    estadosMexico.find(
      (estado) => estado.nombre === nombreEstado,
    )?.ciudades ?? []
  );
}

export function obtenerMunicipiosPorCiudad(
  nombreEstado: string,
  nombreCiudad: string,
): string[] {
  const ciudades = obtenerCiudadesPorEstado(nombreEstado);

  return (
    ciudades.find(
      (ciudad) => ciudad.nombre === nombreCiudad,
    )?.municipios ?? []
  );
}
